use_frameworks!
platform :ios, '12.1'

target 'BikeBLE_Tests' do
  
  pod 'BikeBLE', :path => '../'
  pod 'Bluejay'
  pod 'XCGLogger', '~> 6.1.0'
  pod 'PromiseKit', '~> 6.8.3'
  pod 'ZIPFoundation', '~> 0.9.9'
  
end

